# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e16eed70cc60592c50115b16e3b64001335fe7e03fc0dcf5a81a77e884c4071dd1cadeed11a73dbb7871d4514f48eccc4d8c3b99d5f973f09c0e0516393aca0

test:
  secret_key_base: 7e94a5555142464a4f3c0c1818dfa0b96ca42b752e85bef06e876dbc8ef3fbb56e1dfba905c6fec6249af951dcc66f6c329b842d6320ce6aa032a3fb4344a749

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
